---
  ### General Config

  ## start a tensorboard server
  tensorboard: true


  ### Debug Config

  ## pause after each step
  # debug_evaluate_pause: true

  ## log session run calls
  # debug_runs: true
  # debug_runs_ignored: [predict]

  ## write activation summaries to tensorboard
  # debug_activations: true

  ## write gradient summaries to tensorboard
  # debug_gradients: true

  ## session run tracing
  # debug_trace: true

  ## print periodic memory information
  # debug_memory: true

  ## add numerics checks (NaNs, etc.)
  # debug_numerics: true


  ### Session Config

  session_config:
    gpu_options:
      allow_growth: true
    # log_device_placement: true
