--- # Ant
  env: glearn.envs.ant:AntEnv
  batch_size: 128

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:FullyConnectedLayer
            args:
              hidden_sizes: [128, 128]
  # policy: glearn.policies:RandomPolicy  # HACK

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      optimizer: adam
      learning_rate: 2.0e-4
      episodes: 5000
      keep_prob: 0.8
      epsilon: [1, 0.1, 10]
      evaluate_interval: 1
