--- # Ant
  import: base

  env: glearn.envs.ant:AntEnv
  batch_size: 128

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [128, 128, 8]
        optimizer: adam
        learning_rate: 2.0e-4
  # policy: glearn.policies:RandomPolicy  # HACK

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      episodes: 5000
      keep_prob: 0.8
      epsilon: [1, 0.1, 10]
      evaluate_interval: 1
