--- # CartPole
  import: _base

  env: CartPole-v0
  # seeds: [809142917, 3412706144, 1757722874]

  batch_size: 32
  episode_buffer:
    size: 100000

  policy:
    name: glearn.policies:QNetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [32, 32]
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [0]
              activation: null
        optimizer: adam
        learning_rate: 0.001
        # max_grad_norm: 5

  trainer:
    name: glearn.trainers:DeepQNetworkTrainer
    args:
      epochs: 1600
      evaluate_interval: 10
      epsilon: [1, 0.01, 450]
      gamma: 0.999
      target_update_steps: 10

  # sweeps:
  #   learning_rate: [1.0e-4, 1.0e-3, 1.0e-2]
