--- # CartPole
  import: _base

  env: CartPole-v0

  # batch_size: 2000  # FIXME why doesn't batch_episodes=false work?

  batch_size: 10
  episode_buffer:
    batch_episodes: true

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [10]
          - name: glearn.networks:CategoricalDistributionLayer
        optimizer: adam
        learning_rate: 0.02

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      gamma: 0.99
      epochs: 1000
      evaluate_interval: 10
