--- # CartPole
  import: _base

  env: CartPole-v0
  batch_size: 0  # 4096
  # seeds: [3765698959, 1907813997]

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        # weight_decay: TODO - network param
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [10]  # [128]
              activation: tensorflow.nn:tanh
          - name: glearn.networks:CategoricalDistributionLayer
        optimizer: adam
        learning_rate: 0.02  # [4.0e-3, 0.5, 1000]
        # max_grad_norm: 0.1  # 5

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      # V:
      #   layers:
      #     - name: glearn.networks:DenseLayer
      #       args:
      #         hidden_sizes: [128, 1]
      #   optimizer: adam
      #   learning_rate: [4.0e-3, 0.5, 1000]
      #   max_grad_norm: 0.1  # 5
      gamma: 0.99  # 0.9
      epochs: 1000
      # keep_prob: 0.8
      # epsilon: [1, 0.1, 400]
      evaluate_interval: 10

  # sweeps:
  #   max_grad_norm: [1.0e-3, 1.0e-2, 1.0e-1, 1.0]
  #   learning_rate: [[1.0e-2, 0.5, 1000], [1.0e-3, 0.5, 1000], [1.0e-4, 0.5, 1000]]
