--- # CartPole
  import: _base

  env: CartPole-v0

  batch_size: 10
  episode_buffer:
    batch_episodes: true

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [10]
          - name: glearn.networks:CategoricalDistributionLayer
        optimizer: adam
        learning_rate: 0.02
        max_grad_norm: 0.5

  trainer:
    name: glearn.trainers:AdvantageActorCriticTrainer
    args:
      epochs: 1000
      evaluate_interval: 10
      gamma: 0.99
      gae_lambda: 0.95

      V_coef: 0.5
      V:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [128]
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [1]
              activation: null
        optimizer: adam
        learning_rate: 0.2
        max_grad_norm: 50
