--- # CartPole
  import: _base

  env: CartPole-v0
  batch_size: 10

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [16]
          - name: glearn.networks:CategoricalDistributionLayer
        optimizer: adam
        learning_rate: 1.0e-2
        # max_grad_norm: 5

  trainer:
    name: glearn.trainers:ReinforceTrainer
    args:
      gamma: 0.99
      epochs: 2000
      # keep_prob: 0.8
      # epsilon: [1, 0.1, 10]
      evaluate_interval: 10

  # sweeps:
  #   learning_rate: [2.0e-2, 3.0e-2, 4.0e-2, 5.0e-2]
