--- # CartPole
  import: _base

  env: CartPole-v0
  batch_size: 256
  seeds: [3765698959, 1907813997]

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        weight_decay: TODO - network param
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [128]
          - name: glearn.networks:CategoricalDistributionLayer
        optimizer: adam
        learning_rate: [4.0e-3, 0.5, 1000]
        max_grad_norm: 0.1  # 5

  trainer:
    name: glearn.trainers:ReinforceTrainer
    args:
      gamma: 0.9
      epochs: 600
      # keep_prob: 0.8
      # epsilon: [1, 0.1, 400]
      evaluate_interval: 10

  # sweeps:
  #   max_grad_norm: [1.0e-3, 1.0e-2, 1.0e-1, 1.0]
  #   learning_rate: [[0.5e-3, 0.5, 1000], [1.0e-3, 0.5, 1000], [2.0e-3, 0.5, 1000], [4.0e-3, 0.5, 1000]]
