--- # CIFAR-10
  dataset: cifar10
  batch_size: 128
  
  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:Conv2dLayer
            args:
              filters: [[5, 5, 64]]
              max_pool_k: 3
              lrn: [false, 1, 0.0001111111111, 0.75]
          - name: glearn.networks:Conv2dLayer
            args:
              filters: [[5, 5, 64]]
              max_pool_k: 3
              lrn: [true, 1, 0.0001111111111, 0.75]
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [384, 192]

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      optimizer: sgd
      learning_rate: 0.1
      lr_decay: 0.1
      lr_decay_epochs: 350
      epochs: 1500
      # keep_prob: 0.8
      evaluate_interval: 20

  viewer:
    name: glearn.viewers.advanced_viewer:AdvancedViewer
    args:
      zoom: 2
      modes:
        - name: glearn.viewers.modes:CNNViewerMode
          args:
            visualize_grid: [10, 10]
