--- # CIFAR-10
  import: _base

  dataset: cifar10
  batch_size: 128
  
  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:Conv2dLayer
            args:
              filters: [[5, 5, 64]]
              max_pool_k: 3
              lrn: [false, 1, 0.0001111111111, 0.75]
              # weights_initializer:
              #   name: tensorflow:truncated_normal_initializer
              #   args:
              #     stddev: 5.0e-2
          - name: glearn.networks:Conv2dLayer
            args:
              filters: [[5, 5, 64]]
              max_pool_k: 3
              lrn: [true, 1, 0.0001111111111, 0.75]
              # weights_initializer:
              #   name: tensorflow:truncated_normal_initializer
              #   args:
              #     stddev: 5.0e-2
              biases_initializer:
                name: tensorflow:constant_initializer
                args:
                  value: 0.1
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [384, 192]
              weight_decay: 0.004
              # weights_initializer:
              #   name: tensorflow:truncated_normal_initializer
              #   args:
              #     stddev: 0.04
              biases_initializer:
                name: tensorflow:constant_initializer
                args:
                  value: 0.1
          - name: glearn.networks:CategoricalDistributionLayer
        optimizer: adam
        learning_rate: 2.0e-4
        lr_decay: 0.5
        lr_decay_intervals: 40
        max_grad_norm: 5

  trainer:
    name: glearn.trainers:SupervisedTrainer
    args:
      epochs: 1500
      keep_prob: 0.8
      evaluate_interval: 100

  viewer:
    name: glearn.viewers.advanced_viewer:AdvancedViewer
    args:
      zoom: 2
      modes:
        - name: glearn.viewers.modes:CNNViewerMode
          args:
            visualize_grid: [10, 10]

  # local run overrides
  local:
    trainer:
      args:
        evaluate_interval: 100
