--- # Digit Repeat
  dataset: digit_repeat
  batch_size: 20
  timesteps: 35
  multithreaded: true

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:LSTMLayer
            args:
              hidden_sizes: [128]
              embedding_lookup: true  # HACK - should be false
        loss: glearn.networks.losses:sequence_loss

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      optimizer: adam
      learning_rate: 2.0e-4
      epochs: 60
      keep_prob: 0.5
      max_grad_norm: 5
      evaluate_interval: 6

  viewer:
    name: glearn.viewers.advanced_viewer:AdvancedViewer
    args:
      zoom: 1
      modes:
        - name: glearn.viewers.modes:RNNViewerMode
