--- # Digit Repeat
  import: _base

  dataset: digit_repeat
  batch_size: 20
  timesteps: 35
  multithreaded: true

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:LSTMLayer
            args:
              hidden_sizes: [128]
              embedding_lookup: true  # HACK - should be false
        optimizer: adam
        learning_rate: 2.0e-4
        max_grad_norm: 5

  trainer:
    name: glearn.trainers:SupervisedTrainer
    args:
      epochs: 200
      keep_prob: 0.5
      evaluate_interval: 20

  viewer:
    name: glearn.viewers.advanced_viewer:AdvancedViewer
    args:
      zoom: 1
      modes:
        - name: glearn.viewers.modes:RNNViewerMode
