--- # Maze
  env:
    name: glearn.envs.maze:MazeEnv
    args:
      maze_size: [10, 10]
  batch_size: 128

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      layers:
        - name: glearn.network:FullyConnectedLayer
          args:
            hidden_sizes: [128, 128]
  # policy: glearn.policies:RandomPolicy  # HACK

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      optimizer: adam
      learning_rate: 2.0e-4
      episodes: 5000
      keep_prob: 0.8
      epsilon: [1, 0.1, 10]
      evaluate_interval: 1
