--- # Maze
  import: _base

  env:
    name: glearn.envs.maze:MazeEnv
    args:
      maze_size: [10, 10]
  batch_size: 128

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [128, 128]
        optimizer: adam
        learning_rate: 2.0e-4

  trainer:
    name: glearn.trainers:ReinforcementTrainer
    args:
      epochs: 500
      keep_prob: 0.8
      evaluate_interval: 1
