--- # MNIST VAE
  import: _base

  dataset: mnist
  batch_size: 128
  
  trainer:
    name: glearn.trainers:VAEGANTrainer
    args:

      encoder:  # encoder network
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [500]
              activation: tensorflow.nn:leaky_relu
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [500]
              activation: tensorflow.nn:tanh
          - name: glearn.networks:NormalDistributionLayer
            args:
              size: 100  # encoding size
        optimizer: adam
        learning_rate: 2.0e-4
        # batch_norm: true

      decoder:  # decoder network
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [500]
              activation: tensorflow.nn:tanh
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [500]
              activation: tensorflow.nn:leaky_relu
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [784]
              activation: tensorflow.nn:sigmoid
        optimizer: adam
        learning_rate: 2.0e-4
        # batch_norm: true

      discriminator:  # discriminator network
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [1024, 512, 256]
              activation: tensorflow.nn:leaky_relu
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [1]
              activation: tensorflow.nn:sigmoid
        optimizer: adam
        learning_rate: 2.0e-4
        # batch_norm: true
      discriminator_steps: 1

      epochs: 200
      keep_prob: 0.9
      evaluate_interval: 20

  # viewer:
  #   name: glearn.viewers.advanced_viewer:AdvancedViewer
  #   args:
  #     zoom: 2
  #     modes:
  #       - name: glearn.viewers.modes:CNNViewerMode
  #         args:
  #           visualize_grid: [10, 10]
