--- # MNIST CVAE
  import: _base

  dataset: mnist
  batch_size: 128
  one_hot: true

  trainer:
    name: glearn.trainers:VariationalAutoencoderTrainer
    args:
      conditional: true

      encoder:  # encoder network
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [500]
              activation: tensorflow.nn:elu
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [500]
              activation: tensorflow.nn:tanh
          - name: glearn.networks:NormalDistributionLayer
            args:
              size: 20  # encoding size
        optimizer: adam
        learning_rate: 1.0e-3

      decoder:  # decoder network
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [500]
              activation: tensorflow.nn:tanh
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [500]
              activation: tensorflow.nn:elu
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [784]
              activation: tensorflow.nn:sigmoid

      epochs: 20
      keep_prob: 0.9
      evaluate_interval: 20

  # viewer:
  #   name: glearn.viewers.advanced_viewer:AdvancedViewer
  #   args:
  #     zoom: 2
  #     modes:
  #       - name: glearn.viewers.modes:CNNViewerMode
  #         args:
  #           visualize_grid: [10, 10]
