--- # Mountain Car
  import: _base

  env: MountainCarContinuous-v0

  batch_size: 5
  episode_buffer:
    batch_episodes: true

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [64, 64]
          - name: glearn.networks:NormalDistributionLayer
            # args:
            #   squash: true
          # - name: glearn.networks:DiscretizedDistributionLayer
          #   args:
          #     divs: 5
        optimizer: adam
        learning_rate: 2.0e-4  # 7.0e-4 (baselines)
        max_grad_norm: 0.5

  trainer:
    name: glearn.trainers:AdvantageActorCriticTrainer
    args:
      epochs: 500
      evaluate_interval: 10
      gamma: 0.99
      ent_coef: 0.01
      V_coef: 0.5
      V:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [64, 64, 1]
        optimizer: adam
        learning_rate: 1.0e-4  # 7.0e-4 (baselines
        max_grad_norm: 0.5
