--- # Mountain Car
  import: _base

  env: MountainCarContinuous-v0
  batch_size: 128

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [400]
          - name: glearn.networks:NormalDistributionLayer
            # args:
            #   squash: true
        optimizer: adam
        learning_rate: 3.0e-4
        max_grad_norm: 5

  trainer:
    name: glearn.trainers:ReinforcementTrainer
    args:
      episodes: 1000
      # keep_prob: 0.8
      evaluate_interval: 10
