--- # Mountain Car
  import: base

  env: MountainCarContinuous-v0
  batch_size: 128

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        optimizes: false
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [200]
          - name: glearn.networks:NormalDistributionLayer

  trainer:
    name: glearn.trainers:ActorCriticTrainer
    args:
      critic:
        optimizer: adam
        learning_rate: 0.00046415888336127773
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [100]
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [1]
              activation: null
      optimizer: adam
      learning_rate: 1.0e-4
      ent_coef: 2.782559402207126e-05
      gamma: 0.98999999999999999
      episodes: 5000
      keep_prob: 0.8
      epsilon: [1, 0.1, 10]
      evaluate_interval: 1

      