--- # Mountain Car
  import: _base

  env: MountainCarContinuous-v0
  batch_size: 24  # 256

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      scale_output: true
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [400]
              activation: tensorflow.nn:tanh
          # - name: glearn.networks:DenseLayer
          #   args:
          #     hidden_sizes: [0]
          #     activation: tensorflow.nn:sigmoid
          - name: glearn.networks:NormalDistributionLayer
            # args:
            #   squash: true
          # - name: glearn.networks:DiscretizedDistributionLayer
          #   args:
          #     divs: 5
        optimizer: adam
        learning_rate: 1.0e-4
        max_grad_norm: 5

  trainer:
    name: glearn.trainers:ReinforceTrainer
    args:
      epochs: 500
      # keep_prob: 0.8
      evaluate_interval: 1
