--- # Pendulum
  env: Pendulum-v0
  batch_size: 128

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        optimizes: false
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [128, 128]
          - name: glearn.networks:DistributionLayer
            args:
              mean_scale: 2

  trainer:
    name: glearn.trainers:ActorCriticTrainer
    args:
      critic:
        optimizer: adam
        learning_rate: 2.0e-4
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [128, 128]
      optimizer: adam
      learning_rate: 1.0e-4
      gamma: 0.95
      episodes: 5000
      keep_prob: 0.8
      epsilon: [1, 0.1, 10]
      evaluate_interval: 1

      