--- # Pendulum
  import: _base

  env: Pendulum-v0
  batch_size: 128

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [128, 128]
          - name: glearn.networks:NormalDistributionLayer
            # args:
            #   squash: true
        optimizer: adam
        learning_rate: 2.0e-4
        max_grad_norm: 5

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      episodes: 5000
      keep_prob: 0.8
      epsilon: [1, 0.1, 10]
      evaluate_interval: 1

      