--- # PTB
  import: _base

  dataset: ptb
  batch_size: 20
  timesteps: 35
  multithreaded: true

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:LSTMLayer
            args:
              hidden_sizes: [650]
              embedding_lookup: true
        optimizer: adam
        learning_rate: 2.0e-4
        # lr_decay: 0.5
        # lr_decay_intervals: 6
        max_grad_norm: 5

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      epochs: 39
      keep_prob: 0.5
      evaluate_interval: 10

  viewer:
    name: glearn.viewers.advanced_viewer:AdvancedViewer
    args:
      zoom: 1
      modes:
        - name: glearn.viewers.modes:RNNViewerMode
