--- # PTB
  dataset: ptb
  batch_size: 20
  timesteps: 35
  multithreaded: true

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:LSTMLayer
            args:
              hidden_sizes: [650]
              embedding_lookup: true
        loss: glearn.networks.losses:sequence_loss

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      optimizer: sgd
      learning_rate: 1.0
      lr_decay: 0.5
      lr_decay_epochs: 6
      epochs: 39
      keep_prob: 0.5
      max_grad_norm: 5
      evaluate_interval: 10

  viewer:
    name: glearn.viewers.advanced_viewer:AdvancedViewer
    args:
      zoom: 1
      modes:
        - name: glearn.viewers.modes:RNNViewerMode
