--- # RNN
  include: default.yaml
  
  policy: glearn.policies:RNN
  
  optimizer: sgd  # FIXME - was hardcoded in rnn.py
  learning_rate: 1
  lr_decay: 0.93
  multithreaded: true
  keep_prob: 0.5
  timesteps: 5
  max_grad_norm: 5

  hidden_size: 128
  hidden_depth: 1
  cell_args:
    forget_bias: 1
