--- # Space Invaders
  import: _base

  env: SpaceInvaders-v0
  batch_size: 128
    
  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:Conv2dLayer
            args:
              filters: [[5, 5, 32], [5, 5, 64]]
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [3136, 1024]
          - name: glearn.networks:CategoricalDistributionLayer
        optimizer: adam
        learning_rate: 2.0e-4

  trainer:
    name: glearn.trainers:ReinforcementTrainer
    args:
      epochs: 500
      keep_prob: 0.8
      evaluate_interval: 1

  viewer:
    name: glearn.viewers.advanced_viewer:AdvancedViewer
    args:
      zoom: 4
      modes:
        - name: glearn.viewers.modes:CNNViewerMode
