--- # Space Invaders
  env: SpaceInvaders-v0
  batch_size: 128
    
  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [256, 256]

  trainer:
    name: glearn.trainers:PolicyGradientTrainer
    args:
      optimizer: adam
      learning_rate: 2.0e-4
      episodes: 5000
      keep_prob: 0.8
      evaluate_interval: 1

  viewer:
    name: glearn.viewers:AdvancedViewer
    args:
      zoom: 4
