--- # Test RNN
  import: _base

  dataset: digit_repeat
  batch_size: 20
  timesteps: 35
  multithreaded: true

  # debug_embeddings: true
  # debug_embedded: true

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:LSTMLayer
            args:
              hidden_sizes: [128]
              embedding_lookup: true  # HACK - should be false
        optimizer: adam
        learning_rate: 2.0e-4
        max_grad_norm: 5

  trainer:
    name: glearn.trainers:SequenceTrainer
    args:
      epochs: 400
      keep_prob: 0.5
      evaluate_interval: 100
