--- # Test Deep Q Network
  import: _base

  env:
    name: glearn.envs.reinforcement_test:ReinforcementTestEnv
    args:
      action_size: 8
      desired: [1, 2, 3]
      desired_sequence: true
      discrete: true
      max_undesired_steps: 100
      sparse_reward: false

  batch_size: 20
  episode_buffer:
    size: 1000

  policy:
    name: glearn.policies:QNetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [16]
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [0]
              activation: null
        optimizer: adam
        learning_rate: 0.001

  trainer:
    name: glearn.trainers:DeepQNetworkTrainer
    args:
      gamma: 0.99
      evaluate_interval: 100
      max_episode_time: 0.1
