--- # Test Advantage Actor Critic
  import: _base

  env:
    name: glearn.envs.reinforcement_test:ReinforcementTestEnv
    args:
      max_undesired_steps: 10
      # mode: decaying
      # reward_multiple: 0
      # mode: sparse
  batch_size: 20

  policy:
    name: glearn.policies:NetworkPolicy
    args:
      network:
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [16]
          - name: glearn.networks:CategoricalDistributionLayer
        optimizer: adam
        learning_rate: 2.0e-1

  trainer:
    name: glearn.trainers:AdvantageActorCriticTrainer
    args:
      critic:
        optimizer: adam
        learning_rate: 2.0e-1
        layers:
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [16]
          - name: glearn.networks:DenseLayer
            args:
              hidden_sizes: [1]
              activation: null
      gamma: 0.99
      evaluate_interval: 100
      max_episode_time: 0.1
