#!/usr/bin/env python3

import click
from glearn.train import train


@click.command()
@click.argument("config_path")
@click.option("--version", "-v", default=None)
@click.option("--render/--no-render", default=True)
@click.option("--profile/--no-profile", default=False)
def main(config_path, version, render, profile):
    train(config_path, version=version, render=render, profile=profile)


if __name__ == "__main__":
    main()
