--- # CNN
  include: default.yaml

  policy: glearn.policies:CNNPolicy

  optimizer: adam
  learning_rate: 2.0e-4
  keep_prob: 0.8

  filters:
    - [5, 5, 32]
    - [5, 5, 64]
  strides: 1
  padding: "SAME"
  max_pool_k: 2
  fc_layers:
    - 3136
    - 1024
